trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: First
    displayName: "First stage"
    jobs:
      - job: A
        steps:
          - script: echo Hello, world!
            displayName: "Run a one-line script"

          - script: |
              free -m
              echo ""
              df -h
              echo ""
              env -0 | sort -z | tr '\0' '\n'
            displayName: "Script: Dump environment"

  - stage: Second
    displayName: Second stage manual
    trigger: manual
    jobs:
      - job: DeployJob
        steps:
          - script: echo Hello, world!
            displayName: "Run a one-line script"

          - script: |
              free -m
              echo ""
              df -h
              echo ""
              env -0 | sort -z | tr '\0' '\n'
            displayName: "Script: Dump environment"

  - stage: Third
    displayName: Third stage deployment
    jobs:
      - deployment: DeployWeb
        environment: "Environment1"
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, world!
                  displayName: "Run a one-line script"

                - script: |
                    free -m
                    echo ""
                    df -h
                    echo ""
                    env -0 | sort -z | tr '\0' '\n'
                  displayName: "Script: Dump environment"

  - stage: Fourth
    displayName: Fourth stage manual
    trigger: manual
    dependsOn: Third
    jobs:
      - job: DeployJob
        steps:
          - script: echo Hello, world!
            displayName: "Run a one-line script"

          - script: |
              free -m
              echo ""
              df -h
              echo ""
              env -0 | sort -z | tr '\0' '\n'
            displayName: "Script: Dump environment"

  - stage: Fifth
    displayName: Fifth stage deployment
    dependsOn: Third
    trigger: manual
    jobs:
      - deployment: DeployWeb
        environment: "Environment2"
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, world!
                  displayName: "Run a one-line script"

                - script: |
                    free -m
                    echo ""
                    df -h
                    echo ""
                    env -0 | sort -z | tr '\0' '\n'
                  displayName: "Script: Dump environment"